import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AI } from './rsc/AI'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(inter.className, 'h-full')}>
        <AI>{children}</AI>
      </body>
    </html>
  )
}
