/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IJJwf02ZeKI
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { ReactNode } from 'react'

type Props = {
  date: Date
  message: ReactNode
}

export function MessageBox({ date, message }: Props) {
  return (
    <div className="space-y-4">
      <div className="flex-1 space-y-2">
        <div className="rounded-lg bg-gray-100 p-4 text-sm dark:bg-gray-800">
          <p>{message}</p>
        </div>
        <div className="text-xs text-gray-500 dark:text-gray-400">
          {date.toDateString()}
        </div>
      </div>
    </div>
  )
}
