/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IJJwf02ZeKI
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { WeatherInfo } from '@/app/api/external/fetchWeather'
import { Card } from '@/components/ui/card'
import Image from 'next/image'

type Props = {
  info: WeatherInfo
}

export function WeatherCard({ info }: Props) {
  return (
    <div className="flex">
      <Card className=" bg-white shadow-md rounded-lg flex-grow-0 flex-shrink-0 flex-auto">
        <div className="p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Image
                src={`https:` + info.current?.condition.icon}
                alt={info.current.condition.text}
                height={24}
                width={24}
              />
              <div>
                <span className="pr-4 text-4xl font-bold text-gray-200">
                  {info.current.temp_c}°C
                </span>
                <span className="text-lg text-gray-500">
                  {info.current.condition.text}
                </span>
                <p className="text-sm text-gray-500 mt-1">
                  {info.location.name}
                </p>
              </div>
            </div>
          </div>
        </div>
      </Card>
    </div>
  )
}
